spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: ${DB_PASSWORD}
    platform: MYSQL
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  tomcat:
    max-swallow-size: -1
photos:
  path: "photos/"
  resource: "file:/app/photos/"
contacts:
  path: "contacts/"
  json-file: "contacts.json"
about-me:
  path: "about-me/"
  json-file: "about-me.json"
projects:
  path: "project-photos/"
  resource: "file:/app/project-photos/"
